global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    metrics_path: '/metrics' # FastAPI default provided by starlette-prometheus or custom
    static_configs:
      - targets: ['backend:8000']
  
  # - job_name: 'milvus'
  #   static_configs:
  #     - targets: ['milvus:9091']
